### ISSUE TITLE
Viterbi calculations in the NTI region are incorrect

### ISSUE THREAD

**Issue by dunleavy005** [matsengrp/linearham#32]
Currently, we calculate viterbi probabilities and paths through the NTI region by marginalizing over the hidden NTI states and just recording the best NTI exit point.  We should, instead, be recording the viterbi probability at each NTI base, and store backpointers to the optimal hidden NTI bases (i.e. we shouldn't be calculating the NTI likelihood, we should be doing a standard HMM viterbi procedure in this region).

(Side note: We also should be doing proper viterbi analysis, instead of just getting viterbi paths for each VDJ smooshed chain, and then max'ing over all VDJ chains, but this is up for discussion).

**Comment by matsen** [comment]
Re first point, it seems to me that we can do exactly the same as this:

![](https://camo.githubusercontent.com/f4a3b1df577a084fde8a87d9bcd89af49f6e46fe/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f3131323730382f31393730333333312f34396638313061342d396162382d313165362d386561612d3962323736366263353437652e706e67)

except rather than doing matrix multiplication (e.g. in A_0 \cdot T) we take the max (rather than sum) of the component-wise products. We also record this index.

We also need to have someplace to store this information. We could have another Smooshish type that holds this information, does not have `viterbi_` be the same as `marginal_` as it is now.


I don't understand your second point-- the Viterbi path for the whole thing is the best path among those for the various chains, right?

**Comment by dunleavy005** [comment]
Agree to the first point! Maybe even store it in NTInsertion class, but never initialize it if we want the marginal prob?

To your second comment, yes. But if we have tons of chains due to there being tons of SW matches, then doing a final max over all those wont be cheap? Its a minor thing if we have few matches per read (as our example files have).  The sketch i have for how to do proper viterbi is not clean, so practically if you feel the number of SW matches is usually small most times then it shouldn't hurt to do that final max.

**Comment by dunleavy005** [comment]
(Personally I'd rather not change so much of what we've already done for a proper viterbi if the gains aren't so high)

**Comment by matsen** [comment]
> Agree to the first point! Maybe even store it in NTInsertion class, but never initialize it if we want the marginal prob?

Yep!

For your second point, I'm not sure what you are proposing as an alternate means of doing viterbi.

**Comment by dunleavy005** [comment]
It would involve keeping track of not only max transition points but also max germline genes. Right now we only do it over transition points.

**Comment by matsen** [comment]
It seems to me that we can't get any more efficient than using the Chain structure, right? And at the end of the Chain inferences we will have the Viteri probabilities. From there it's just taking a max over a vector. 

(Pretty sure I'm missing your point here...)

**Comment by dunleavy005** [comment]
Its just that the max over all VDJ chains could be expensive because its max over (#V) * (#D) * (#J) elements, which could be costly depending on how many there are of V's, D's, J's, yeah?

**Comment by matsen** [comment]
Yes, but are you proposing a means of getting around that?

**Comment by dunleavy005** [comment]
yes, but A) you seem ok with max'ing over all VDJ chains? and B) it might drastically change the code structure so do we care enough to do it?

**Comment by matsen** [comment]
You really have me curious, but I can guess what you're proposing by your comments above. It seems like for this round of coding we can focus on getting the existing branch merged and closing the issues as they stand, which AFAIK just requires more tests. 

Then we can consider optimizing both the marginal and the viterbi calculations with more specialized code?

**Comment by matsen** [comment]
(BTW, partis will only serve I think 3 V's 5 D's and 4 J's, which is 60 combinations max)

**Comment by dunleavy005** [comment]
we are going bayesian! viterbi unnecessary!
