### ISSUE TITLE
Can't seem to get linearham to run -- probably an issue understanding inputs

### ISSUE THREAD

**Issue by wfs-lilly** [matsengrp/linearham#57]
Hi,

I successfully ran a partis partition job as follows:

 /partis/bin/partis partition --infname ./data/TSPN-Bulk-VH-M6_S1_L001_RM_001.Annot.seq.dedup2.fasta --outfname ./TSPN-m6-dedup2.part.yaml --locus igh --initial-germline-dir ./data/germlines/aliva --sanitize-input-germlines --leave-default-germline --n-procs=8
 
(I had to use a partis Docker instance -- for some reason the partis code inside the linearham Docker image doesn't have your recent fixes, nor mafft.)

Then, using the linearham Docker image I try this:

scons --run-linearham --cluster-ind=0 --partis-yaml-file=../TSPN-m6-dedup2.part.yaml --outdir=../_output/ --parameter-dir=../_output/._data_TSPN-Bulk-VH-M6_S1_L001_RM_001.Annot.seq.dedup2/ 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.

(I've mapped in the linearham directory with all executables to be just below the directory where I created the partis outputs:
ls ..
TSPN-m6-dedup2.part.yaml  data	     lham.recipe  node	  plots  run1.view_output.log
_output	c		  hat3.seed  linearham	  output  pre
).

I don't really know scons and can't seem to get it to print out its steps.  I tried deducing the command line to run outside of scons, but can't seem to get the parameters straight there.

My aim is to get the linearham analysis, hopefully in a graphical form as in your paper, for cluster 0 of the partis analysis.  I'd really appreciate any help.

Thanks,
Bill

**Comment by eharkins** [comment]
Hi Bill,

Sorry you're having trouble! 

> the partis code inside the linearham Docker image doesn't have your recent fixes

this is accurate, since I haven't updated the partis submodule in linearham since @psathyrella's changes that I think you are [referring to](https://github.com/matsengrp/linearham/issues/55#issuecomment-552693395). I can get on this but in the meantime, since you successfully ran partis with the partis Docker container, let's focus on getting Linearham to run for you for now:

> nor mafft

is not accurate regarding the latest linearham image (matsengrp/linearham:latest) since I have added mafft after #56. Hopefully you should not need mafft if you are using `--partis-yaml-file`, but the more important point is that this tells us you don't have the latest linearham image, so let's rule out that updating doesn't solve your problem.

Try doing `docker pull matsengrp/linearham:latest` and then rerunning the container with your command and let me know if you are still having trouble.

Thanks,
Eli

**Comment by eharkins** [comment]
Regarding : 
> I've mapped in the linearham directory with all executables to be just below the directory where I created the partis outputs

, if you are able to share your docker command, that will help me try to understand if it is an issue understanding inputs as you say. Thanks!

**Comment by wfs-lilly** [comment]
Thanks for the help.

We can’t run docker on our HPC systems and instead have a container system called singularity-- https://sylabs.io/docs/.  I guess it is consider more secure in some way.
singularity will pull docker images from DockerHub and convert them to its own format, which is a “sif” file – you’ll see that in my command line.

One aspect of it (or possibly our config) is that all container file systems are mounted read-only, so I have to explicitly override the /node directory to make that writable.

My command to start the container is this:

singularity shell -B node:/node ../linearham_latest.sif

After I execute that command I’m “in” the container.

Singularity linearham_latest.sif:~/v5x3838/linearham> df -h
Filesystem                                         Size  Used Avail Use% Mounted on
overlay                                             16M   12K   16M   1% /
devtmpfs                                           126G     0  126G   0% /dev
tmpfs                                              126G  8.0M  126G   1% /dev/shm
/dev/mapper/rootvg-rootlv                           30G   24G  7.0G  77% /etc/hosts
gulf.d51.lilly.com:/nasexp10/v5x3838               579G  404G  175G  70% /home/v5x3838
/dev/mapper/rootvg-tmplv                            50G   47M   50G   1% /tmp
/dev/mapper/rootvg-varlv                            20G  666M   20G   4% /var/tmp
nfs-ssd-1fs:/ifs/lrl/users/v5x3838/linearham       3.8P  3.1P  562T  85% /lrlhps/users/v5x3838/linearham
tmpfs                                               16M   12K   16M   1% /etc/group
nfs-ssd-1fs:/ifs/lrl/users/v5x3838/linearham/node  3.8P  3.1P  562T  85% /node
Singularity linearham_latest.sif:~/v5x3838/linearham>

This is my file layout:

Singularity linearham_latest.sif:/linearham> cd /home/v5x3838/v5x3838/linearham
Singularity linearham_latest.sif:~/v5x3838/linearham> pwd
/home/v5x3838/v5x3838/linearham
Singularity linearham_latest.sif:~/v5x3838/linearham> ls -l
total 117211
-rw-r--r--  1 v5x3838 sashare 106173662 Nov 14 18:21 TSPN-m6-dedup2.part.yaml
drwxr-xr-x  3 v5x3838 sashare       106 Nov 15 15:17 _output
drwxr-xr-x  3 v5x3838 sashare        98 Nov 13 16:39 data
-rw-------  1 v5x3838 sashare         0 Nov 13 16:46 hat3.seed
-rwxr--r--  1 v5x3838 sashare      1368 Nov  6 21:45 lham.recipe
drwxr-xr-x 10 v5x3838 sashare       414 Nov  6 21:54 linearham
drwxr-xr-x  3 v5x3838 sashare        25 Nov 13 16:50 node
drwxr-xr-x  2 v5x3838 sashare         0 Nov 13 16:40 output
drwxr-xr-x  3 v5x3838 sashare        28 Nov 14 21:36 plots
-rw-------  1 v5x3838 sashare         0 Nov 13 16:46 pre

Singularity linearham_latest.sif:~/v5x3838/linearham> ls -ld /node
drwxr-xr-x 3 v5x3838 sashare 25 Nov 13 16:50 /node

Singularity linearham_latest.sif:~/v5x3838/linearham> ls -l /linearham/
total 132
-rw-r--r-- 1 root root   1315 Nov 13 14:47 Dockerfile
-rw-r--r-- 1 root root 106281 Nov 13 14:47 Doxyfile
-rw-r--r-- 1 root root   6907 Nov 13 14:47 README.md
-rw-r--r-- 1 root root  17625 Nov 13 14:47 SConstruct
drwxr-xr-x 5 root root     60 Nov 12 16:42 _build
drwxr-xr-x 4 root root    278 Nov 12 13:31 data
drwxr-xr-x 2 root root    117 Nov 12 13:31 doc_images
drwxr-xr-x 9 root root    189 Nov 12 13:31 lib
drwxr-xr-x 2 root root    232 Nov 12 13:31 scripts
drwxr-xr-x 2 root root    354 Nov 12 13:31 src
drwxr-xr-x 2 root root     77 Nov 12 13:31 templates
drwxr-xr-x 2 root root     48 Nov 12 13:31 test
-rw-r--r-- 1 root root   2043 Nov 13 14:47 wercker.yml

Then I try to run using the command shown at DockerHub and making an attempt to refer to the outputs of my partis run.

Singularity linearham_latest.sif:/linearham> scons --run-linearham --cluster-ind=0 --partis-yaml-file=/home/v5x3838/v5x3838/linearham/TSPN-m6-dedup2.part.yaml --outdir=/home/v5x3838/v5x3838/linearham/_output/ --parameter-dir=/home/v5x3838/v5x3838/linearham/_output/._data_TSPN-Bulk-VH-M6_S1_L001_RM_001.Annot.seq.dedup2/
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
Singularity linearham_latest.sif:/linearham>

Clearly this is scons thinking that none of its build targets need to be executed, but I can’t really remove any outputs and do not know how to force it.  I tried to figure out the partis command being executed, but the SConstruct remaps the parameters and I couldn’t get them right.

William F. Smith
Bioinformatician
BCforward
Lilly Biotechnology Center
10290 Campus Point Dr.
San Diego, CA 92121
smith_william1@network.lilly.com<mailto:smith_william1@network.lilly.com>

CONFIDENTIALITY NOTICE: This email message (including all attachments) is for the sole use of the intended recipient(s) and may contain confidential information. Any unauthorized review, use, disclosure, copying or distribution is strictly prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by eharkins** [comment]
We also use singularity on our HPC for the same reasons.

I am able to reproduce your issue in both regular Docker and Singularity. After a lot of trying to figure out what is causing scons to think that the target outputs exist, I think it has something to do with `--outdir` being an absolute path. No idea why this causes the issue, but I had success doing something like the following:

```
cd ~
mkdir lh_output
singularity shell --pwd /linearham -B $(pwd)/lh_output:/linearham/output linearham.sif
```
and then running the following once in the container:
```
scons --run-partis --fasta-path=data/liao_dataset.fasta --all-clonal-seqs \
    && scons --run-linearham --template-path=templates/revbayes_template.rev --mcmc-iter=25 --mcmc-thin=1 --tune-iter=0 --seed-seq=KC576081.1
```

Here I am just using the example linearham command from the Dockerfile, but the point is I am just using the default output dir and binding that with singularity to `~/lh_output` by doing `-B $(pwd)/lh_output:/linearham/output`.

This way I can just use the standard output directory, since there seems to be some issue with specifying output directories like you have done with `outdir=/home/v5x3838/v5x3838/linearham/_output/` and when I tried similar absolute paths.

Hope this helps and stay posted in case I figure out what scons is thinking when it is telling us `scons: '.' is up to date.`

**Comment by wfs-lilly** [comment]
Thank you -- this got me running.

**Comment by eharkins** [comment]
@wfs-lilly to be clear, if by 

> the linearham analysis, hopefully in a graphical form as in your paper

you mean the lineage plots like this:

![Screen Shot 2019-11-18 at 2 31 15 PM](https://user-images.githubusercontent.com/12140437/69099712-4a44d180-0a10-11ea-9fd9-3b62fefc74c9.png)

, you need to tell linearham about a sequence of interest in your cluster via `--seed-seq` so that it can create plots like this one which visualize probable lineages to the sequence of interest.

Sorry I didn't mention this before, I overlooked your stated aim initially in this issue. You can still run Linearham in the absence of a sequence of interest, which will infer naive sequences along with other cluster properties, including probable phylogenetic trees. See [the "output files" section of the readme](https://github.com/matsengrp/linearham#output-files) for details about these outputs.
