### ISSUE TITLE
Use new partis fcn add_seqs_to_line()

### ISSUE THREAD

**Issue by psathyrella** [matsengrp/linearham#74]
It's hard to believe when we talked about this before I didn't realize how easy it would be, but I wrote a function to add new sequences (i.e. inferred intermediates from a phylo program) to an existing partis annotation without running partis, it just uses a mafft step if there's some constant region cruft. I'm pretty sure there's at least one place in linearham that we want to use this rather than running partis from scratch?
https://github.com/matsengrp/linearham/blob/master/SConstruct#L285
https://github.com/psathyrella/partis/blob/dev/python/utils.py#L512

**Comment by eharkins** [comment]
I thought we only run annotate in linearham when we don't have an annotation at all, and are just passing in a fasta of clonal family sequences, in which case we probably don't have an annotation to add those sequences to and need to run annotate (otherwise we should be running LH with `--run-linearham --partis-yaml-file` instead of `--run-partis --fasta-path`). 

Maybe there is still a case where we could use your function in linearham but for the case I describe it seems like we'll still need to run annotate. Does that make sense?

**Comment by psathyrella** [comment]
Ah, ok, no you're probably right. I don't remember how it works. I know, how about Jared can check ;-)

**Comment by psathyrella** [comment]
i added a command line script if that's an easier interface

https://github.com/psathyrella/partis/blob/dev/bin/add-seqs-to-outputs.py

**Comment by psathyrella** [comment]
Indeed, it doesn't seem like there's a place where this needs to be used
