### ISSUE TITLE
Add virtual destructors for all classes

### ISSUE THREAD

**Issue by matsen** [matsengrp/linearham#8]
`virtual ~ClassName() {};`

Note: destructors unwind, meaning that they will call all superclass destructors.

**Comment by matsen** [comment]
Not for all. Lord Meyers summarizes: "declare a virtual destructor in a class if and only if it contains at least one virtual function."

cc @bcclaywell

**Comment by dunleavy005** [comment]
Also , are they only really important in the above case OR if we have raw pointer memory in a class that needs free'ing? Just a learning Q

**Comment by bcclaywell** [comment]
It definitely matters if the derived class has additional dynamically-allocated memory that the destructor is in charge of freeing. I think it matters even if it doesn't, but *does* have additional stack-allocated data members the base class doesn't have. Imagine you have a `Base` class with no member variables, while the `Derived` class declares a `Widget` object member variable. Without a virtual destructor, destroying an object of type `Derived` via the `Base` destructor wouldn't necessarily destroy the `Widget`, even though the `Widget` wasn't dynamically-allocated. Or it might be undefined behavior; I'm having trouble finding something that says one way or the other. In any case, you'd want a virtual destructor so that you didn't have to worry about it.

**Comment by bcclaywell** [comment]
Found it. From [cppreference.com](http://en.cppreference.com/w/cpp/language/destructor):

```
Deleting an object through pointer to base invokes undefined behavior unless the destructor in the base class is virtual.
```

**Comment by dunleavy005** [comment]
Awesome, thanks for the info!

**Comment by dunleavy005** [comment]
https://isocpp.org/wiki/faq/virtual-functions#virtual-dtors, another reference for why `virtual` destructors are needed.
